platform :osx, '10.10'

def shared_pods
  pod 'WultraPassphraseMeter', :path => '../../../'
  pod 'WultraPassphraseMeter/Dictionary_czsk', :path => '../../../'
  pod 'WultraPassphraseMeter/Dictionary_en', :path => '../../../'
end

target 'PassMeterTester' do
  shared_pods
end
