platform :ios, '10.0'

def shared_pods
  pod 'WultraPassphraseMeter', :path => '../../../../'
  pod 'WultraPassphraseMeter/Dictionary_czsk', :path => '../../../../'
  pod 'WultraPassphraseMeter/Dictionary_en', :path => '../../../../'
  pod 'WultraPassphraseMeter/Dictionary_ro', :path => '../../../../'
end

target 'PassMeterExample' do
  shared_pods
end

target 'PassMeterExampleTests' do
  shared_pods
end
