platform :ios, '10.0'

def shared_pods
  pod 'WultraPassMeter', :path => '../../../../'
  pod 'WultraPassMeter/Dictionary_czsk', :path => '../../../../'
  pod 'WultraPassMeter/Dictionary_en', :path => '../../../../'
end

target 'PassMeterExample' do
  shared_pods
end
