name: build

on:
  push:
    branches:
      - develop
      - master
      - releases/*
  pull_request:

jobs:
  android:
    name: Build Android
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build the Android aars
        run: pushd Source/src_android && ./gradlew clean build
  ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Build the iOS xcframeworks
        run: ./scripts/build.sh
