name: tests

on:
  push:
    branches:
      - develop
      - master
      - releases/*
  pull_request:
  schedule:
    - cron: '25 6 * * *'

jobs:
  tests:
    name: Tests
    runs-on: macos-11
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./Source/tests/test.sh
